import type { Metadata } from "next"
import Head from "next/head"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { SiteHeader } from "@/components/header"
import { SiteFooter } from "@/components/footer"
import React from "react";
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "LeetBoard",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head><link rel="icon" href="/leet-board/public/favicon.ico" sizes="google" style={{ width: "20px", height: "20px" }} /></Head>
      <body className={"bg-neutral-100 dark:bg-neutral-900"}>
        <meta name="viewport" content={"width=device-width, initial-scale=1.0"} />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader></SiteHeader>
          {children}
          <SiteFooter></SiteFooter>
        </ThemeProvider>
      </body>
    </html>
  )
}
