import type { Metadata } from "next"
import Head from "next/head"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { SiteHeader } from "@/components/header"
import { SiteFooter } from "@/components/footer"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "LeetBoard",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head><link rel="icon" href="/favicon.ico" sizes="any" /></Head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader></SiteHeader>
          {children}
          <SiteFooter></SiteFooter>
        </ThemeProvider>
      </body>
    </html>
  )
}
